from fpdf import FPDF
import streamlit as st
from datetime import date
import pandas as pd
import hashlib
import numpy as np
import os
import google.generativeai as genai
from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import RealDictCursor
from sqlalchemy import create_engine

load_dotenv() # Load environment variables from .env file

# --- 1. STREAMLIT PAGE CONFIGURATION ---
st.set_page_config(page_title="EduManage Pro", layout="wide", page_icon="⚡")

# --- 2. ENTERPRISE CSS STYLING ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    /* Hide Streamlit Branding for White-Label Look */
    #MainMenu {visibility: hidden;}
    header {visibility: hidden;}
    footer {visibility: hidden;}

    html, body, [class*="css"], .stApp {
        font-family: 'Inter', sans-serif !important;
        background-color: #121212 !important; /* Carbon Black */
        color: #EAEAEA !important;
        font-size: 14px !important;
    }

    .stApp {
        background: #121212 !important;
    }

    h1, h2, h3 {
        font-weight: 600 !important;
        letter-spacing: -0.025em !important;
        color: #F9FAFB !important;
    }

    .stExpander, .stForm {
        background: #1E1E1E !important; /* Darker Carbon */
        border: 1px solid #2E2E2E !important;
        border-radius: 6px !important;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1) !important;
        margin-bottom: 0.5rem;
    }

    div.stButton > button {
        background: #B45309; /* Amber 700 */
        border: 1px solid #92400E; /* Amber 800 */
        color: #FFFFFF; 
        padding: 0.35rem 1rem;
        border-radius: 4px;
        font-weight: 500;
        font-size: 0.875rem;
        transition: background-color 0.2s;
        width: 100%;
    }

    div.stButton > button:hover {
        background: #92400E;
        border-color: #78350F;
    }

    [data-testid="metric-container"] {
        background: #1E1E1E;
        border: 1px solid #2E2E2E;
        border-radius: 6px;
        padding: 1rem;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
    }
    
    [data-testid="stMetricValue"] {
        color: #FBBF24 !important; /* Amber 400 */
        font-weight: 600 !important;
        font-size: 1.75rem !important;
    }
    
    [data-testid="stMetricLabel"] {
        font-size: 0.75rem !important;
        color: #A1A1AA !important; /* Zinc 400 */
        font-weight: 600 !important;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }

    .stTabs [data-baseweb="tab-list"] {
        gap: 24px;
        border-bottom: 1px solid #2E2E2E;
    }
    .stTabs [data-baseweb="tab"] {
        color: #71717A; /* Zinc 500 */
        padding: 0.5rem 0;
        font-size: 0.875rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.025em;
    }
    .stTabs [aria-selected="true"] {
        color: #FBBF24 !important;
        border-bottom: 2px solid #FBBF24 !important;
    }

    .stTextInput input, .stNumberInput input, .stSelectbox > div > div {
        border-radius: 4px !important;
        background-color: #121212 !important;
        border: 1px solid #3F3F46 !important; /* Zinc 700 */
        color: #EAEAEA !important;
        font-size: 0.875rem !important;
        padding: 0.4rem 0.75rem !important;
    }
    .stTextInput input:focus, .stNumberInput input:focus, .stSelectbox > div > div:focus {
        border-color: #FBBF24 !important;
        box-shadow: 0 0 0 1px #FBBF24 !important;
    }
    
    hr {
        border-color: #2E2E2E !important;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. DATABASE SETUP ---
@st.cache_resource(ttl=600)
def init_db():
    # Connect using environment variable or Streamlit secrets
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        try:
            db_url = st.secrets["DATABASE_URL"]
        except Exception:
            st.error("DATABASE_URL not found. Please set it in .env or Streamlit Secrets.")
            st.stop()
            
    try:
        conn = psycopg2.connect(db_url)
        c = conn.cursor(cursor_factory=RealDictCursor)
        
        c.execute('''
            CREATE TABLE IF NOT EXISTS students (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                student_class TEXT,
                monthly_fees NUMERIC,
                parent_name TEXT,
                contact TEXT,
                is_paid BOOLEAN DEFAULT FALSE,
                is_archived BOOLEAN DEFAULT FALSE,
                last_paid_date TEXT
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS expenses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                item TEXT NOT NULL,
                amount NUMERIC,
                date TEXT
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                task TEXT NOT NULL,
                is_done BOOLEAN DEFAULT FALSE
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS attendance (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
                date TEXT,
                status TEXT
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS exams (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
                exam_name TEXT,
                score NUMERIC,
                total_marks NUMERIC,
                date TEXT
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS admin_auth (
                id INT PRIMARY KEY,
                password_hash TEXT
            )
        ''')
        
        # Seed the default admin password if the auth table is empty
        c.execute("SELECT password_hash FROM admin_auth WHERE id=1")
        if not c.fetchone():
            default_hash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9"
            c.execute("INSERT INTO admin_auth (id, password_hash) VALUES (1, %s)", (default_hash,))
            
        conn.commit()
        return conn
    except psycopg2.OperationalError as e:
        st.error("🚨 **Database Connection Rejected by Supabase**")
        st.warning("If your database password has special characters (like `@`, `#`, `?`), it breaks the connection URL! You must URL-encode them. (For example, change `@` to `%40` in your password inside the URL).")
        st.info(f"Technical Details: {e}")
        st.stop()

def get_db_connection():
    # Now securely cached with a 10-minute Time-To-Live to prevent crashing the connection pool
    return init_db()

conn = get_db_connection()

# --- 4. SECURE AUTHENTICATION & ADMIN ---

def get_password_hash():
    c = conn.cursor(cursor_factory=RealDictCursor)
    c.execute("SELECT password_hash FROM admin_auth WHERE id=1")
    return c.fetchone()['password_hash']

def set_password_hash(new_hash):
    c = conn.cursor()
    c.execute("UPDATE admin_auth SET password_hash=%s WHERE id=1", (new_hash,))
    conn.commit()

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if not st.session_state.logged_in:
    st.markdown("<br><br><br>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown("<h2 style='text-align: center; color: #F9FAFB;'>Authentication Required</h2>", unsafe_allow_html=True)
        st.markdown("<p style='text-align: center; color: #9CA3AF;'>Enter the master password to access the system.</p>", unsafe_allow_html=True)
        
        password = st.text_input("Master Password", type="password", placeholder="••••••••")
        if st.button("Authenticate"):
            hashed_pw = hashlib.sha256(password.encode()).hexdigest()
            if hashed_pw == get_password_hash():
                st.session_state.logged_in = True
                st.rerun()
            else:
                st.error("Authentication failed. Invalid credentials.")
    st.stop() # Stops the rest of the application from rendering if not logged in

# --- 5. PREMIUM PDF GENERATOR (Fixed Bytearray Error) ---
def generate_pdf(name, parent_name, class_name, amount, date_str):
    pdf = FPDF()
    pdf.add_page()
    
    # Dark Carbon Header
    pdf.set_fill_color(29, 29, 29)
    pdf.rect(0, 0, 210, 40, 'F')
    
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(251, 191, 36) # Amber/Gold
    pdf.cell(0, 20, "EDU-MANAGE RECEIPT", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, f"Date: {date_str}", ln=True, align='C')
    
    pdf.ln(20)
    
    # Table Content
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(95, 12, "Description", border=1, fill=True)
    pdf.cell(95, 12, "Details", border=1, fill=True, ln=True)
    
    pdf.set_font("Arial", '', 11)
    rows = [
        ("Student Name", name),
        ("Parent Name", parent_name),
        ("Class", class_name),
        ("Amount Paid", f"INR {amount}")
    ]
    
    for label, val in rows:
        pdf.cell(95, 10, label, border=1)
        pdf.cell(95, 10, str(val), border=1, ln=True)
    
    pdf.ln(20)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Status: PAID", ln=True, align='R')
    pdf.set_draw_color(29, 29, 29)
    pdf.line(140, pdf.get_y(), 200, pdf.get_y())
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Authorized Signature", align='R')
    
    return bytes(pdf.output(dest='S'))

# --- 5.1 PREMIUM REPORT CARD PDF GENERATOR ---
def generate_report_card_pdf(name, class_name, att_percent, present_days, total_days, exam_records, date_str):
    pdf = FPDF()
    pdf.add_page()
    
    # Dark Carbon Header
    pdf.set_fill_color(29, 29, 29)
    pdf.rect(0, 0, 210, 40, 'F')
    
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(251, 191, 36) # Amber/Gold
    pdf.cell(0, 20, "ACADEMIC REPORT CARD", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, f"Date Generated: {date_str}", ln=True, align='C')
    
    pdf.ln(20)
    
    # Student Info & Attendance Summary
    pdf.set_text_color(0, 0, 0)
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. Student & Attendance Profile", ln=True, fill=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(100, 10, f"Name: {name}", ln=False)
    pdf.cell(90, 10, f"Class: {class_name}", ln=True, align='R')
    if total_days > 0:
        pdf.cell(100, 10, f"Days Present: {present_days} out of {total_days}", ln=False)
        pdf.cell(90, 10, f"Attendance: {att_percent:.1f}%", ln=True, align='R')
    else:
        pdf.cell(0, 10, "No attendance records available.", ln=True)
        
    pdf.ln(10)
    
    # Exam Scores
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "2. Academic Performance", ln=True, fill=True)
    
    if exam_records:
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(70, 10, "Exam / Test Name", border=1)
        pdf.cell(40, 10, "Date", border=1)
        pdf.cell(40, 10, "Score Obtained", border=1)
        pdf.cell(40, 10, "Percentage", border=1, ln=True)
        
        pdf.set_font("Arial", '', 11)
        for ex in exam_records:
            pct = (ex['score'] / ex['total_marks']) * 100 if ex['total_marks'] > 0 else 0
            pdf.cell(70, 10, str(ex['exam_name']), border=1)
            pdf.cell(40, 10, str(ex['date']), border=1)
            pdf.cell(40, 10, f"{ex['score']} / {ex['total_marks']}", border=1)
            pdf.cell(40, 10, f"{pct:.1f}%", border=1, ln=True)
    else:
        pdf.set_font("Arial", '', 11)
        pdf.cell(0, 10, "No exam records found.", ln=True)
        
    return bytes(pdf.output(dest='S'))

# --- 6. SIDEBAR ---
with st.sidebar:
    st.header("Register New Student")
    reg_name = st.text_input("Name")
    reg_class = st.text_input("Class")
    reg_fees = st.number_input("Monthly Fees", min_value=0, step=100)
    reg_parent = st.text_input("Parent Name")
    reg_contact = st.text_input("Contact Number")

    if st.button("Add Student"):
        if reg_name:
            c = conn.cursor()
            c.execute('''INSERT INTO students (name, student_class, monthly_fees, parent_name, contact, is_paid, is_archived) 
                         VALUES (%s, %s, %s, %s, %s, FALSE, FALSE)''', 
                      (reg_name, reg_class, reg_fees, reg_parent, reg_contact))
            conn.commit()
            st.success("Student added!")
            st.rerun()
        else:
            st.error("Name is required!")
            
    st.divider()
    st.header("Data Management")
    c = conn.cursor()
    c.execute("SELECT * FROM students")
    db_data = c.fetchall()
    if db_data:
        df_export = pd.DataFrame([dict(row) for row in db_data])
        csv_data = df_export.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="Export Data (CSV)",
            data=csv_data,
            file_name="students_export.csv",
            mime="text/csv",
            use_container_width=True
        )
        
    st.divider()
    st.header("Global Search")
    global_search_query = st.text_input("Search students, expenses, tasks...")

    st.divider()
    if st.button("Terminate Session"):
        st.session_state.logged_in = False
        st.rerun()

# --- 7. MAIN DASHBOARD ---
st.markdown(f"<h1 style='border-bottom: 1px solid #2E2E2E; padding-bottom: 0.5rem;'>EduManage Pro <span style='font-size: 0.8rem; background: #1E1E1E; padding: 2px 8px; border-radius: 12px; color: #A1A1AA; vertical-align: middle; margin-left: 8px;'>ADMINISTRATOR</span></h1>", unsafe_allow_html=True)
st.markdown("<p style='color: #6B7280; font-size: 0.875rem; margin-bottom: 2rem;'>Administrative Dashboard & Revenue Management Portal</p>", unsafe_allow_html=True)

if global_search_query:
    st.header(f"Global Search Results for '{global_search_query}'")
    c = conn.cursor()
    query_like = f"%{global_search_query.lower()}%"
    
    # --- Student Search ---
    c.execute("SELECT * FROM students WHERE LOWER(name) LIKE %s", (query_like,))
    found_students = c.fetchall()
    if found_students:
        st.subheader(f"Found {len(found_students)} matching students")
        for s in found_students:
            status_tag = " *(Archived)*" if s.get('is_archived') else ""
            st.markdown(f"- **{s['name']}**{status_tag} (Class: {s['student_class']})")
    
    st.divider()
    # --- Expense Search ---
    c.execute("SELECT * FROM expenses WHERE LOWER(item) LIKE %s", (query_like,))
    found_expenses = c.fetchall()
    if found_expenses:
        st.subheader(f"Found {len(found_expenses)} matching expenses")
        for e in found_expenses:
            st.markdown(f"- **{e['item']}** (Amount: INR {e['amount']}, Date: {e['date']})")

    st.divider()
    # --- Task Search ---
    c.execute("SELECT * FROM tasks WHERE LOWER(task) LIKE %s", (query_like,))
    found_tasks = c.fetchall()
    if found_tasks:
        st.subheader(f"Found {len(found_tasks)} matching tasks")
        for t in found_tasks:
            status = "Done" if t['is_done'] else "Pending"
            st.markdown(f"- **{t['task']}** (Status: {status})")

    if not found_students and not found_expenses and not found_tasks:
        st.info("No results found across students, expenses, or tasks.")

else:
    c = conn.cursor()
    c.execute("SELECT * FROM students ORDER BY name ASC")
    all_db_students = [dict(row) for row in c.fetchall()]
    all_students = [s for s in all_db_students if not s.get('is_archived')]
    archived_students = [s for s in all_db_students if s.get('is_archived')]

    if all_db_students:
        # Metrics
        total_rev = sum(s['monthly_fees'] for s in all_students if s['is_paid'])
        pending_rev = sum(s['monthly_fees'] for s in all_students if not s['is_paid'])
        
        c.execute("SELECT SUM(amount) as tot FROM expenses")
        exp_res = c.fetchone()
        total_exp = exp_res['tot'] if exp_res and exp_res['tot'] else 0
        net_profit = total_rev - total_exp

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Collected Revenue", f"INR {total_rev}")
        m2.metric("Pending Revenue", f"INR {pending_rev}")
        m3.metric("Total Expenses", f"INR {total_exp}")
        m4.metric("Net Profit", f"INR {net_profit}")

        st.divider()

        tab_students, tab_expenses, tab_tasks, tab_analytics, tab_academics, tab_ai, tab_admin = st.tabs(["Directory", "Financials", "Operations", "Analytics", "Academics", "AI Assistant", "Admin Panel"])
        
        with tab_students:
            student_view = st.radio("Directory View", ["Active Students", "Archived Students"], horizontal=True, label_visibility="collapsed")
            search_query = st.text_input("Search Directory", placeholder="Enter student name...")
            
            # Filter Logic
            target_list = all_students if student_view == "Active Students" else archived_students
            display_list = [s for s in target_list if search_query.lower() in s['name'].lower()] if search_query else target_list
        
            # Display Loop
            for s in display_list:
                with st.expander(f"{s['name']}  |  Class: {s['student_class']}"):
                    col1, col2 = st.columns(2)
                    with col1:
                        st.write(f"**Parent:** {s.get('parent_name', 'N/A')}")
                        st.write(f"**Contact:** {s.get('contact', 'N/A')}")
                        contact_num = s.get('contact', '').strip().replace('+', '').replace(' ', '')
                        if contact_num.isdigit():
                            st.markdown(f"<a href='https://wa.me/{contact_num}' target='_blank' style='color:#D97706; text-decoration:none; font-size:0.875rem;'>Contact via WhatsApp ↗</a>", unsafe_allow_html=True)
                    with col2:
                        st.write(f"**Fees:** INR {s['monthly_fees']}")
                        status_text = "Paid" if s['is_paid'] else "Pending"
                        st.write(f"**Status:** {status_text}")
                        if s['is_paid'] and s.get('last_paid_date'):
                            st.caption(f"Last paid on: {s['last_paid_date']}")
        
                    btn_col1, btn_col2, btn_col3, btn_col4 = st.columns(4)
                    
                    # Toggle Status
                    status_txt = "Mark Unpaid" if s['is_paid'] else "Mark Paid"
                    if btn_col1.button(status_txt, key=f"st_{s['id']}"):
                        new_status = False if s['is_paid'] else True
                        c = conn.cursor()
                        if new_status: # Marking as paid
                            today_date_str = date.today().strftime("%Y-%m-%d")
                            c.execute("UPDATE students SET is_paid = %s, last_paid_date = %s WHERE id = %s", (new_status, today_date_str, s['id']))
                        else: # Marking as unpaid
                            c.execute("UPDATE students SET is_paid = %s, last_paid_date = %s WHERE id = %s", (new_status, None, s['id']))
                        conn.commit()
                        st.rerun()
                    
                    # PDF Download
                    if s['is_paid']:
                        today_str = date.today().strftime("%d-%m-%Y")
                        pdf_bytes = generate_pdf(s['name'], s.get('parent_name', 'N/A'), s['student_class'], s['monthly_fees'], today_str)
                        btn_col2.download_button(
                            label="Download Receipt",
                            data=pdf_bytes,
                            file_name=f"Receipt_{s['name']}.pdf",
                            mime="application/pdf",
                            key=f"dl_{s['id']}"
                        )
                    
                    # Edit Student
                    with btn_col3.popover("Modify Record"):
                        with st.form(key=f"edit_form_{s['id']}"):
                            new_name = st.text_input("Name", s['name'])
                            new_class = st.text_input("Class", s['student_class'])
                            new_fees = st.number_input("Monthly Fees", value=float(s['monthly_fees']), step=100.0)
                            new_parent = st.text_input("Parent Name", s.get('parent_name', ''))
                            new_contact = st.text_input("Contact", s.get('contact', ''))
                            if st.form_submit_button("Save"):
                                c = conn.cursor()
                                c.execute('''UPDATE students SET name=%s, student_class=%s, monthly_fees=%s, parent_name=%s, contact=%s WHERE id=%s''', 
                                          (new_name, new_class, new_fees, new_parent, new_contact, s['id']))
                                conn.commit()
                                st.rerun()
                
                    # Archive / Restore / Delete
                    with btn_col4:
                        action_label = "Restore Record" if s.get('is_archived') else "Archive Record"
                        if st.button(action_label, key=f"arc_{s['id']}", use_container_width=True):
                            new_status = False if s.get('is_archived') else True
                            c = conn.cursor()
                            c.execute("UPDATE students SET is_archived = %s WHERE id = %s", (new_status, s['id']))
                            conn.commit()
                            st.rerun()
                        
                        if s.get('is_archived'):
                            if st.button("Delete Permanently", key=f"del_{s['id']}", use_container_width=True):
                                c = conn.cursor()
                                c.execute("DELETE FROM students WHERE id = %s", (s['id'],))
                                c.execute("DELETE FROM attendance WHERE student_id = %s", (s['id'],))
                                c.execute("DELETE FROM exams WHERE student_id = %s", (s['id'],))
                                conn.commit()
                                st.rerun()
                        
        with tab_expenses:
            st.markdown("<h3 style='font-size: 1.1rem; margin-bottom: 1rem;'>Operational Expenses</h3>", unsafe_allow_html=True)
            with st.form("add_expense"):
                e_col1, e_col2 = st.columns(2)
                with e_col1:
                    exp_item = st.text_input("Expense Item (e.g., Zoom Pro, Markers)")
                with e_col2:
                    exp_amount = st.number_input("Amount", min_value=0.0, step=50.0)
                if st.form_submit_button("Add Expense"):
                    if exp_item:
                        c = conn.cursor()
                        c.execute("INSERT INTO expenses (item, amount, date) VALUES (%s, %s, %s)", (exp_item, exp_amount, date.today().strftime("%Y-%m-%d")))
                        conn.commit()
                        st.rerun()
            
            st.divider()
            
            # Fetch unique months for the dropdown
            c.execute("SELECT DISTINCT TO_CHAR(date::DATE, 'YYYY-MM') as ym FROM expenses WHERE date IS NOT NULL ORDER BY ym DESC")
            months = [row['ym'] for row in c.fetchall() if row['ym']]
            
            filter_col1, filter_col2 = st.columns([1, 1])
            with filter_col1:
                selected_month = st.selectbox("Temporal Filter", ["All Time"] + months)
                
            if selected_month == "All Time":
                c.execute("SELECT * FROM expenses ORDER BY date DESC, id DESC")
            else:
                c.execute("SELECT * FROM expenses WHERE TO_CHAR(date::DATE, 'YYYY-MM') = %s ORDER BY date DESC, id DESC", (selected_month,))
                
            expenses = c.fetchall()
            if expenses:
                filtered_total = sum(e['amount'] for e in expenses)
                with filter_col2:
                    st.metric(f"Total ({selected_month})", f"INR {filtered_total}")
                    
                for e in expenses:
                    ec1, ec2, ec3, ec4 = st.columns([2, 1, 1, 1])
                    ec1.write(f"**{e['item']}**")
                    ec2.write(f"INR {e['amount']}")
                    ec3.write(e['date'])
                    if ec4.button("Delete", key=f"del_exp_{e['id']}"):
                        c = conn.cursor()
                        c.execute("DELETE FROM expenses WHERE id=%s", (e['id'],))
                        conn.commit()
                        st.rerun()

        with tab_tasks:
            st.markdown("<h3 style='font-size: 1.1rem; margin-bottom: 1rem;'>Task Management</h3>", unsafe_allow_html=True)
            new_task = st.text_input("New Task", placeholder="e.g., Prepare mock test for Class 10...")
            if st.button("Add Task") and new_task:
                c = conn.cursor()
                c.execute("INSERT INTO tasks (task) VALUES (%s)", (new_task,))
                conn.commit()
                st.rerun()
                
            c.execute("SELECT * FROM tasks")
            tasks = c.fetchall()
            for t in tasks:
                tc1, tc2 = st.columns([4, 1])
                task_label = f"<span style='color: #71717A;'>{t['task']}</span>" if t['is_done'] else f"{t['task']}"
                is_done = tc1.checkbox(task_label, value=bool(t['is_done']), key=f"task_{t['id']}", help="Mark task as complete", unsafe_allow_html=True)
                
                if is_done != bool(t['is_done']):
                    c = conn.cursor()
                    c.execute("UPDATE tasks SET is_done=%s WHERE id=%s", (is_done, t['id']))
                    conn.commit()
                    st.rerun()
                if tc2.button("Delete", key=f"del_task_{t['id']}"):
                    c = conn.cursor()
                    c.execute("DELETE FROM tasks WHERE id=%s", (t['id'],))
                    conn.commit()
                    st.rerun()

        with tab_analytics:
            st.markdown("<h3 style='font-size: 1.1rem; margin-bottom: 1rem;'>System Analytics</h3>", unsafe_allow_html=True)
            df = pd.DataFrame(all_students)
            
            c1, c2, c3 = st.columns(3)
            with c1:
                st.write("**Revenue by Class**")
                if not df.empty and 'student_class' in df.columns:
                    rev_data = df.groupby('student_class')['monthly_fees'].sum()
                    st.bar_chart(rev_data)
                else:
                    st.info("No active data")
                
            with c2:
                st.write("**Students per Class**")
                if not df.empty and 'student_class' in df.columns:
                    class_counts = df['student_class'].value_counts()
                    st.bar_chart(class_counts)
                else:
                    st.info("No active data")
                
            with c3:
                st.write("**Cash Flow**")
                flow_df = pd.DataFrame({
                    "Category": ["Revenue", "Expenses"],
                    "Amount": [total_rev, total_exp]
                })
                st.bar_chart(flow_df.set_index("Category"), color="#D97706")

            st.divider()
            st.write("**Raw Data Table**")
            st.dataframe(df, use_container_width=True)

        with tab_academics:
            st.markdown("<h3 style='font-size: 1.1rem; margin-bottom: 1rem;'>Academic Performance Matrix</h3>", unsafe_allow_html=True)
            if not all_students:
                st.info("No active students available for academic tracking.")
            else:
                student_dict = {f"{s['name']} (Class {s['student_class']})": s['id'] for s in all_students}
                
                top_col1, top_col2 = st.columns([3, 1])
                with top_col1:
                    selected_student_name = st.selectbox("Select Student Profile", list(student_dict.keys()))
                    selected_student_id = student_dict[selected_student_name]
                    
                c.execute("SELECT status FROM attendance WHERE student_id=%s", (selected_student_id,))
                att_rc_records = c.fetchall()
                tot_days = len(att_rc_records)
                pres_days = sum(1 for r in att_rc_records if r['status'] == 'Present')
                att_pct = (pres_days / tot_days * 100) if tot_days > 0 else 0
                
                c.execute("SELECT * FROM exams WHERE student_id=%s ORDER BY id DESC", (selected_student_id,))
                exam_rc_records = c.fetchall()
                
                selected_student_data = next(s for s in all_students if s['id'] == selected_student_id)
                
                with top_col2:
                    st.write("") # Padding to vertically align button with selectbox
                    st.write("")
                    report_pdf = generate_report_card_pdf(
                        selected_student_data['name'], 
                        selected_student_data['student_class'],
                        att_pct, pres_days, tot_days, exam_rc_records, 
                        date.today().strftime("%d-%m-%Y")
                    )
                    st.download_button(
                        label="Generate Report Card",
                        data=report_pdf,
                        file_name=f"ReportCard_{selected_student_data['name'].replace(' ', '_')}.pdf",
                        mime="application/pdf",
                        use_container_width=True
                    )

                st.divider()
                ac_col1, ac_col2 = st.columns(2)

                with ac_col1:
                    st.write("**Mark Attendance**")
                    att_date = st.date_input("Date", value=date.today())
                    att_status = st.radio("Status", ["Present", "Absent"], horizontal=True)
                    if st.button("Save Attendance"):
                        c = conn.cursor()
                        c.execute("SELECT id FROM attendance WHERE student_id=%s AND date=%s", (selected_student_id, att_date.strftime("%Y-%m-%d")))
                        if c.fetchone():
                            st.warning("Attendance already marked for this date.")
                        else:
                            c.execute("INSERT INTO attendance (student_id, date, status) VALUES (%s, %s, %s)", 
                                      (selected_student_id, att_date.strftime("%Y-%m-%d"), att_status))
                            conn.commit()
                            st.success("Attendance saved!")
                            st.rerun()

                    c.execute("SELECT status FROM attendance WHERE student_id=%s", (selected_student_id,))
                    att_records = c.fetchall()
                    if att_records:
                        total_days = len(att_records)
                        present_days = sum(1 for r in att_records if r['status'] == 'Present')
                        att_percent = (present_days / total_days) * 100
                        st.progress(att_percent / 100, text=f"Attendance: {att_percent:.1f}% ({present_days}/{total_days} days present)")

                with ac_col2:
                    st.write("**Record Exam Score**")
                    with st.form(key=f"exam_form"):
                        exam_name = st.text_input("Exam/Test Name")
                        e_col1, e_col2 = st.columns(2)
                        with e_col1:
                            exam_score = st.number_input("Score Obtained", min_value=0.0)
                        with e_col2:
                            exam_total = st.number_input("Total Marks", min_value=1.0, value=100.0)
                        
                        if st.form_submit_button("Save Score") and exam_name:
                            c = conn.cursor()
                            c.execute("INSERT INTO exams (student_id, exam_name, score, total_marks, date) VALUES (%s, %s, %s, %s, %s)",
                                      (selected_student_id, exam_name, exam_score, exam_total, date.today().strftime("%Y-%m-%d")))
                            conn.commit()
                            st.success("Score saved!")
                            st.rerun()

                    c.execute("SELECT * FROM exams WHERE student_id=%s ORDER BY id DESC", (selected_student_id,))
                    exam_records = c.fetchall()
                    if exam_records:
                        st.write("**Recent Scores**")
                        for ex in exam_records:
                            st.markdown(f"• **{ex['exam_name']}**: {ex['score']} / {ex['total_marks']} *(Recorded: {ex['date']})*")

                        # College Level: Machine Learning (Linear Regression Forecast)
                        if len(exam_records) >= 2: #type: ignore
                            st.markdown("**ML Performance Analysis**")
                            chronological_exams = list(reversed(exam_records))
                            x = np.arange(len(chronological_exams))
                            y = np.array([(ex['score'] / ex['total_marks']) * 100 for ex in chronological_exams])
                            
                            m, b = np.polyfit(x, y, 1)

                            # Create a DataFrame for the chart with the trend line
                            trend_line_y = m * x + b
                            chart_data = pd.DataFrame({
                                'Exam': x + 1,
                                'Actual Score (%)': y,
                                'Performance Trend': trend_line_y
                            }).set_index('Exam')

                            st.line_chart(chart_data, color=["#FBBF24", "#A1A1AA"]) # Gold for actual, Gray for trend

                            next_idx = len(x)
                            predicted_score = min(max((m * next_idx) + b, 0), 100)
                            trend = "Improving" if m > 0.5 else "Declining" if m < -0.5 else "Stable"
                            st.metric(label=f"Trend: {trend}", value=f"{predicted_score:.1f}%", help="This is the predicted score for the next exam based on the linear regression model.")

        with tab_ai:
            st.markdown("<h3 style='font-size: 1.1rem; margin-bottom: 1rem;'>AI Database Assistant</h3>", unsafe_allow_html=True)
            st.info("This feature uses Google's Gemini model. Set your `GOOGLE_AI_API_KEY` in a `.env` file to activate.")

            api_key = os.getenv("GOOGLE_AI_API_KEY")

            if not api_key:
                st.warning("Google AI API Key not found. Please create a `.env` file and add `GOOGLE_AI_API_KEY='your-key-here'`.")
            else:
                try:
                    genai.configure(api_key=api_key)
                    model = genai.GenerativeModel('gemini-pro')

                    question = st.text_area("Ask a question about your data...",
                                            placeholder="e.g., 'Who are the top 3 students with the highest exam scores?' or 'Show me all expenses from last month.'")

                    if st.button("Ask AI"):
                        if question:
                            with st.spinner("AI is thinking..."):
                                # Get the database schema
                                c = conn.cursor()
                                c.execute("SELECT table_name, column_name, data_type FROM information_schema.columns WHERE table_schema = 'public';")
                                schema_info = "\n".join([f"{row['table_name']}.{row['column_name']} ({row['data_type']})" for row in c.fetchall()])

                                prompt = f"""
                                You are an expert in converting English questions to SQLite queries.
                                The user's database has the following schema:
                                {schema_info}

                                Convert the following user question into a valid SQLite query. Only return the SQL query and nothing else.
                                Question: "{question}"                                 """
                                response = model.generate_content(prompt)
                                sql_query = response.text.strip().replace("`", "").replace("sql", "")

                                st.code(sql_query, language="sql")

                                # Basic safety check to ensure read-only queries
                                if not sql_query.upper().lstrip().startswith("SELECT"):
                                    st.error("Security Alert: Only SELECT queries are permitted. The AI attempted a non-read operation.")
                                else:
                                    try:
                                        # Use SQLAlchemy engine for Pandas to prevent DBAPI warnings
                                        engine = create_engine(os.environ.get("DATABASE_URL") or st.secrets["DATABASE_URL"])
                                        query_result = pd.read_sql_query(sql_query, engine)
                                        st.dataframe(query_result, use_container_width=True)
                                    except Exception as db_err:
                                        st.error(f"Failed to execute query: {db_err}")
                except Exception as e:
                    st.error(f"An error occurred with the AI model: {e}")

        with tab_admin:
            st.markdown("<h3 style='font-size: 1.1rem; margin-bottom: 1rem;'>System Administration</h3>", unsafe_allow_html=True)
            
            st.markdown("#### Change Master Password")
            with st.form("change_password_form"):
                current_password = st.text_input("Current Password", type="password")
                new_password = st.text_input("New Password", type="password")
                confirm_new_password = st.text_input("Confirm New Password", type="password")

                if st.form_submit_button("Update Master Password"):
                    current_hash = get_password_hash()
                    if hashlib.sha256(current_password.encode()).hexdigest() == current_hash:
                        if new_password == confirm_new_password and new_password:
                            new_hash = hashlib.sha256(new_password.encode()).hexdigest()
                            set_password_hash(new_hash)
                            st.success("Master password has been updated successfully.")
                        else:
                            st.error("New passwords do not match or are empty.")
                    else:
                        st.error("Incorrect current password.")
            
            st.divider()
            st.markdown("#### System Statistics")
            stat_col1, stat_col2, stat_col3 = st.columns(3)
            c = conn.cursor()
            c.execute("SELECT COUNT(*) FROM students WHERE is_archived=FALSE")
            student_count = c.fetchone()[0]
            c.execute("SELECT COUNT(*) FROM expenses")
            expense_count = c.fetchone()[0]
            c.execute("SELECT COUNT(*) FROM tasks")
            task_count = c.fetchone()[0]
            stat_col1.metric("Total Active Students", student_count)
            stat_col2.metric("Total Expenses Logged", expense_count)
            stat_col3.metric("Total Tasks Created", task_count)

            st.divider()
            st.markdown("#### System Backup")
            st.write("The system is now connected to a persistent remote PostgreSQL database.")
            st.info("System backups are handled automatically by the Supabase/PostgreSQL provider.")
    else:
        st.info("System initializing. No records found in the database.")