-- Copy and paste this into the SQL Editor in your Supabase dashboard and click "Run"

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    student_class TEXT,
    monthly_fees NUMERIC,
    parent_name TEXT,
    contact TEXT,
    is_paid BOOLEAN DEFAULT FALSE
);